### ISSUE TITLE
API/gateway naming cleanup

### ISSUE THREAD

**Issue by rtannenbaum** [google/data-transfer-project#235]
portability-gateway was created to avoid a naming conflict as we ported the portability-api server to the new modular structure

Now that we're mostly done migrating that over, we can remove the old portability-api and go with one consistent name, as both API and gateway are used throughout the codebase currently.

We have decided to go with API as the new name instead of gateway.

**Comment by seehamrun** [comment]
remaining todo for this: 

- rename portability-spi-gateway to portability-api-gateway (maybe?)
- rename portability-gateway to portability-api
- rename portability-worker to portability-transfer 

Going to hold off on this for now until we get the demo working and things quick changes die down a bit since this will be a pretty big rename.

**Comment by seehamrun** [comment]
filed #328  and #329  to keep track of remaining renaming tasks.
